- name: IAM | create EKS service role
  iam_role:
    name: "{{ eks_cluster.role_name }}"
    profile: "{{ common.profile }}"
    region: "{{ common.region }}"
    managed_policies:
      - AmazonEKSClusterPolicy
      - AmazonEKSServicePolicy
    assume_role_policy_document: "{{ lookup('file', 'eks-trust-policy.json') }}"
    description: "Allows EKS to manage clusters on your behalf."
  register: eks_cluster_iam_role_results

- name: IAM | create IAM worker node role
  iam_role:
    name: "{{ eks_worker.role_name }}"
    profile: "{{ common.profile }}"
    region: "{{ common.region }}"
    managed_policies:
      - AmazonEKSWorkerNodePolicy
      - AmazonEKS_CNI_Policy
      - AmazonEC2ContainerRegistryReadOnly
    assume_role_policy_document: "{{ lookup('file', 'ec2-trust-policy.json') }}"
  register: eks_worker_iam_role_results